### PR TITLE
Cscetsin 18 fsd harvesting

### PR DESCRIPTION
**Pull request by juholehtonen**
Mapping of old Etsin IDs and 'universe' still coming. These can be reviewed already.

### CODE REVIEW

**Comment by junsk1** [comment]
Proposition: Change ckanext-oaipmh ddi25.py md_format = 'ddi_c' to md_format = 'oai_ddi25' ? Push and change directly to master. Similarly, in ckanext-etsin change in plugin.py line 47?

**Comment by junsk1** [comment]
Still missing legacy pids and access_type.

**Comment by juholehtonen** [comment]
Requested changes added: changed metadata format name, added legacy pids and access type.

**Review by junsk1 — APPROVED** [review]
OK

**Pull request merged**
